graph LR
    A[alter < 20] 
    A-->|yes| B[Kesha: 'Tik Tok']
    A-->|no| C[Alter < 30]
    C-->|yes| D[Destiny's Child: 'Say My Name']
    C-->|no| E[alter < 40]
    E-->|yes| F[Mariah Carey: 'Vision of love']
    E-->|no| G[Blondie: 'Call me']