graph LR
    A[uhrzeit < 5] 
    A-->|yes| B[Gute Nacht]
    A-->|no| C[Uhrzeit < 11]
    C-->|yes| D[Guten Morgen]
    C-->|no| E[Uhrzeit < 18]
    E-->|yes| F[Guten Tag]
    E-->|no| G[Uhrzeit < 22]
    G-->|yes| H[Guten Abend]
    G-->|no| I[Gute Nacht]