# Programmieren I {#sec-intro-cig1}

In diesem Block bekommt ihr euren ersten Kontakt mit Python. Er soll einen Einstieg in die Programmierwelt von Python bieten und spezifisch zeigen, wie man räumliche Fragestellungen mit frei verfügbarer Software lösen kann. 
Die Voraussetzung für diesen Kurs ist eine Offenheit, neue Tools und Ansätze kennen zu lernen, die Bereitschaft für lösungsorientiertes Arbeiten sowie etwas Hartnäckigkeit. 

## Vorbereitung

Um Python sinnvoll lernen und anwenden zu können, müsst ihr ein paar Programme installieren. Die folgenden Kapitel leiten euch dabei an.

### Positron IDE

Um mit `R` zu Programmieren habt ihr bisher in RStudio gearbeitet. RStudio ist eine sogenannte "Integrierte Entwicklungsumgebung" (*Integrated development environment*, IDE), wo ihr eure R-Scripts entwicklen konntet. Posit, die Herstellen von RStudio, haben eine zweite IDE erstellt, die von der Bedienung sehr ähnlich ist wie RStudio, aber Python besser unterstützt. Diese IDE heisst *Positron* und ist ebenfalls kostenlos und mit freiem Quellcode verfügbar.  

Ladet die neuste Version von Positron für euer Betriebssystem herunter (siehe [hier](https://github.com/posit-dev/positron/releases)) und installiert diese. 

### Python 

Im Modul Angewandte Geoinformatik benutzen wir Python. Mit der Installation von ArcGIS sollte die Python bereits installiert sein. Es muss also lediglich getestet werden, ob dies auch wie erwartet funktioniert. Bitte führt die Instruktionen unter dem Punkt [Mit ArcGIS Installation](#sec-mit-arcgis) durch.

:::{.callout-note}
Wer lieber auf einem anderen Betriebssystem als Windows arbeiten möchte, sollte es für den Teil Programmieren I - III auch können. In diesem Fall braucht es aber ein bisschen Vorbereitung. Befolgt in diesem Fall die Schritte unter dem Punkt [Ohne ArcGIS Installation](#sec-ohne-arcgis) durch.

:::


#### Mit ArcGIS Installation (v.a. Windows Nutzer){#sec-mit-arcgis}

Um zu testen, ob die Installation bei Dir auch funktioniert, musst Du die paar Schritte ausführen:

1. Python Command Prompt suchen und starten
2. Folgender Befehl eingeben: 

    ```bash
    python3 --version
    ```
3. Wenn der obige Befehl eine Fehlermeldung verursacht, bitte mit der der Anleitung [Ohne ArcGIS Installation](#sec-ohne-arcgis) weiterfahren.


#### Ohne ArcGIS Installation (v.a. Mac / Linux Nutzer){#sec-ohne-arcgis}

Wer keine ArcGIS installation hat, sollte folgendermassen vorgehen:

1. Überprüfe, ob Python ≥ 3.11 installiert ist. Tippe dafür folgenden Befehl in den Terminal:

    ```bash
    python3 --version
    ```
2. Wenn die Python nicht vorhanden oder die Version < 3.11 ist, solltet ihr eine aktuelle Version von Python installieren: <https://www.python.org/downloads/>
3. Installiert Miniconda von dieser Website: <https://docs.conda.io/projects/miniconda/en/latest/>

### Conda

Mit der Software `conda` verwalten wir unsere Python Packages in sogenannte *conda environments*. Erstellt die environment für den ersten Kurstag mit folgendem Befehl im Terminal:  

```bash
conda create --name geopython1
conda activate geopython1   # Windows nutzer: activate geopython1
conda install -c conda-forge jupyterlab pandas
```



## Daten

Im Kurs werdet ihr nachstehende Datensätze benötigen, die ihr im Moodlekurs unter *Programmieren I → Datensätze* herunterladen könnt.

| Datensatz              | Beschreibung          |
|:-----------------------|:----------------------|                     
| zeckenstiche.csv       | Eine CSV mit 10 Zeckenstich-Meldungen im Kanton Zürich |
| zeckenstiche_full.csv  | Eine CSV mit 1'076 Zeckenstich-Meldungen im Kanton Zürich |
| wald.gpkg | Ein Geodatensatz mit einem flächendeckenden (lückenlosen) Polygon, welche den Kanton Zürich in "Wald" und "nicht Wald" unterscheidet |
: Datensätze für den Teil "Programmieren I - III" {#tbl-datensaetze}

<!-- :::{.callout-note}
## Übungsziele

- Python kennen lernen, erste Interaktionen mit Python durch die Commandline
- Erste Erfahrungen mit JupyterLab sammeln
- Die wichtigsten Datentypen in Python kennen lernen (`bool`, `str`, `int`, `float`, `list`, `dict`)
- Pandas DataFrames kennen lernen und einfache Manipulationen durchführen 
::: -->
