# Primitive Datentypen

Bei primitiven Datentypen handelt es sich um die kleinste Einheit der Programmiersprache, sie werden deshalb auch "atomare Datentypen" genannt. Alle komplexeren Datentypen (Tabellarische Daten, Bilder, Geodaten) basieren auf diesen einfachen Strukturen. Die für uns wichtigsten Datentypen lauten: *Boolean*, *String*, *Integer* und *Float*. Das sind ähnliche Datentypen wie ihr bereits aus R kennt:

| Python | R | Beschreibung | Beispiel | in Python | 
|:---|:---|:---|:---|:---|
| Boolean | Logical | Logische Werte ja / nein | Wahr / Falsch | `regen = True` |
| String | Character | Textinformation | Bern, Luzern | `stadt = "Bern"` |
| Integer | Integer | Zahl ohne Nachkommastelle | Anzahl Einwohner | `bern = 133115` |
| Float | Double | Zahl mit Nachkommastelle | Temperatur | `temp = 22.5` |


:::{#tip-positron-project .callout-tip}

## Positron Projekt erstellen

Um die nachfolgenden Codebeispiele selbst ausprobieren zu können, müsst ihr 

1. *Positron* starten
2. In Positron ein neues Projekt erstellen (⨁ New → New Project → Python Project)
   - Project Name: *Python_Code* (unser Vorschlag)
   - Parent Directory: `Pfad\zu\deinem\Modul-AGI-Kurs\Programmieren1`
3. Python Umgebung auswählen:
   - *Use an existing Python installation* auswählen
   - Python Interpreter: Hier die Umgebung *geopython1* suchen
   - Klick *Create* → Current Window
4. File direkt abspeichern: <kbd>Ctrl</kbd> + <kbd>S</kbd> (sinnvollen Namen mit endung `.py` geben)
4. Im neuen Textfile Pythoncode schreiben
5. Mit <kbd>Ctrl</kbd> + <kbd>Enter</kbd> Pythoncode ausführen
:::


## Boolean

Hierbei handelt es sich um den einfachsten Datentyp. Er beinhaltet nur zwei Zustände: *Wahr* oder *Falsch*. In Python werden diese mit `True` oder `False` definiert (diese Schreibweise muss genau beachtet werden). Beispielsweise sind das Antworten auf geschlossene Fragen.

```{python}
regen = True # "es regnet"

sonne = False # "die Sonne scheint nicht"

type(sonne)
```

Um zu prüfen, ob ein bestimmter Wert `True` oder `False` ist verwendet man `is True`. Will man also fragen ob es regnet, wir dies folgendermassen formuliert:

```{python}
# regnet es?
regen is True
```

Ob die Sonne scheint, lautet folgendermassen (natürlich müssen dazu die Variabel `sonne` bereits existieren):

```{python}
# scheint die Sonne?
sonne is True
```

## String

In sogenannten *Strings* werden Textinformationen gespeichert. Beispielsweise können das die Namen von Ortschaften sein.

```{python}
stadt = "Bern"
land = "Schweiz"

type(stadt)
```

Strings können mit `+` miteinander verbunden werden

```{python}
stadt + " ist die Hauptstadt der " + land
```

## Integer

In *Integer* werden ganzzahlige Werte gespeichert, beispielsweise die Anzahl Einwohner einer Stadt. 

```{python}
bern_einwohner = 133115

type(bern_einwohner)
```

## Float

Als *Float* werden Zahlen mit Nachkommastellen gespeichert, wie zum Beispiel die Temperatur in Grad Celsius.

```{python}
bern_flaeche = 51.62

type(bern_flaeche)
```
